services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  shortener:
    build:
      context: .
      dockerfile: Dockerfile.shortener
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./apps/shortener/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shortener.rule=PathPrefix(`/`)"
      - "traefik.http.routers.shortener.priority=1"
      - "traefik.http.services.shortener.loadbalancer.server.port=3000"


  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./apps/auth/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.priority=2"
      - "traefik.http.services.auth.loadbalancer.server.port=3001"

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  web:
    driver: bridge